/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedReportsRouteImport } from './routes/_protected/reports'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedDonationsIndexRouteImport } from './routes/_protected/donations/index'
import { Route as ProtectedUsersUserIdRouteImport } from './routes/_protected/users/$userId'
import { Route as ProtectedDonationsDonationIdRouteImport } from './routes/_protected/donations/$donationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDonationsIndexRoute = ProtectedDonationsIndexRouteImport.update({
  id: '/donations/',
  path: '/donations/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersUserIdRoute = ProtectedUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDonationsDonationIdRoute =
  ProtectedDonationsDonationIdRouteImport.update({
    id: '/donations/$donationId',
    path: '/donations/$donationId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/reports': typeof ProtectedReportsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/donations/$donationId': typeof ProtectedDonationsDonationIdRoute
  '/users/$userId': typeof ProtectedUsersUserIdRoute
  '/donations/': typeof ProtectedDonationsIndexRoute
  '/users/': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/reports': typeof ProtectedReportsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/donations/$donationId': typeof ProtectedDonationsDonationIdRoute
  '/users/$userId': typeof ProtectedUsersUserIdRoute
  '/donations': typeof ProtectedDonationsIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/reports': typeof ProtectedReportsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/donations/$donationId': typeof ProtectedDonationsDonationIdRoute
  '/_protected/users/$userId': typeof ProtectedUsersUserIdRoute
  '/_protected/donations/': typeof ProtectedDonationsIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/donations/$donationId'
    | '/users/$userId'
    | '/donations/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/donations/$donationId'
    | '/users/$userId'
    | '/donations'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/dashboard'
    | '/_protected/reports'
    | '/_protected/settings'
    | '/_protected/donations/$donationId'
    | '/_protected/users/$userId'
    | '/_protected/donations/'
    | '/_protected/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/donations/': {
      id: '/_protected/donations/'
      path: '/donations'
      fullPath: '/donations/'
      preLoaderRoute: typeof ProtectedDonationsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users/$userId': {
      id: '/_protected/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof ProtectedUsersUserIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/donations/$donationId': {
      id: '/_protected/donations/$donationId'
      path: '/donations/$donationId'
      fullPath: '/donations/$donationId'
      preLoaderRoute: typeof ProtectedDonationsDonationIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedReportsRoute: typeof ProtectedReportsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedDonationsDonationIdRoute: typeof ProtectedDonationsDonationIdRoute
  ProtectedUsersUserIdRoute: typeof ProtectedUsersUserIdRoute
  ProtectedDonationsIndexRoute: typeof ProtectedDonationsIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedReportsRoute: ProtectedReportsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedDonationsDonationIdRoute: ProtectedDonationsDonationIdRoute,
  ProtectedUsersUserIdRoute: ProtectedUsersUserIdRoute,
  ProtectedDonationsIndexRoute: ProtectedDonationsIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
