/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedZonesRouteImport } from './routes/_protected/zones'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedReportsRouteImport } from './routes/_protected/reports'
import { Route as ProtectedModerationRouteImport } from './routes/_protected/moderation'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedDonationsIndexRouteImport } from './routes/_protected/donations/index'
import { Route as ProtectedUsersUserIdRouteImport } from './routes/_protected/users/$userId'
import { Route as ProtectedDonationsDonationIdRouteImport } from './routes/_protected/donations/$donationId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedZonesRoute = ProtectedZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedModerationRoute = ProtectedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDonationsIndexRoute = ProtectedDonationsIndexRouteImport.update({
  id: '/donations/',
  path: '/donations/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersUserIdRoute = ProtectedUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDonationsDonationIdRoute =
  ProtectedDonationsDonationIdRouteImport.update({
    id: '/donations/$donationId',
    path: '/donations/$donationId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/moderation': typeof ProtectedModerationRoute
  '/reports': typeof ProtectedReportsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/zones': typeof ProtectedZonesRoute
  '/donations/$donationId': typeof ProtectedDonationsDonationIdRoute
  '/users/$userId': typeof ProtectedUsersUserIdRoute
  '/donations/': typeof ProtectedDonationsIndexRoute
  '/users/': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/moderation': typeof ProtectedModerationRoute
  '/reports': typeof ProtectedReportsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/zones': typeof ProtectedZonesRoute
  '/donations/$donationId': typeof ProtectedDonationsDonationIdRoute
  '/users/$userId': typeof ProtectedUsersUserIdRoute
  '/donations': typeof ProtectedDonationsIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/moderation': typeof ProtectedModerationRoute
  '/_protected/reports': typeof ProtectedReportsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/zones': typeof ProtectedZonesRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/donations/$donationId': typeof ProtectedDonationsDonationIdRoute
  '/_protected/users/$userId': typeof ProtectedUsersUserIdRoute
  '/_protected/donations/': typeof ProtectedDonationsIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/moderation'
    | '/reports'
    | '/settings'
    | '/zones'
    | '/donations/$donationId'
    | '/users/$userId'
    | '/donations/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/moderation'
    | '/reports'
    | '/settings'
    | '/zones'
    | '/donations/$donationId'
    | '/users/$userId'
    | '/donations'
    | '/users'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_protected/analytics'
    | '/_protected/moderation'
    | '/_protected/reports'
    | '/_protected/settings'
    | '/_protected/zones'
    | '/_protected/'
    | '/_protected/donations/$donationId'
    | '/_protected/users/$userId'
    | '/_protected/donations/'
    | '/_protected/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/zones': {
      id: '/_protected/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ProtectedZonesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/moderation': {
      id: '/_protected/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ProtectedModerationRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/donations/': {
      id: '/_protected/donations/'
      path: '/donations'
      fullPath: '/donations/'
      preLoaderRoute: typeof ProtectedDonationsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users/$userId': {
      id: '/_protected/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof ProtectedUsersUserIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/donations/$donationId': {
      id: '/_protected/donations/$donationId'
      path: '/donations/$donationId'
      fullPath: '/donations/$donationId'
      preLoaderRoute: typeof ProtectedDonationsDonationIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedModerationRoute: typeof ProtectedModerationRoute
  ProtectedReportsRoute: typeof ProtectedReportsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedZonesRoute: typeof ProtectedZonesRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDonationsDonationIdRoute: typeof ProtectedDonationsDonationIdRoute
  ProtectedUsersUserIdRoute: typeof ProtectedUsersUserIdRoute
  ProtectedDonationsIndexRoute: typeof ProtectedDonationsIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedModerationRoute: ProtectedModerationRoute,
  ProtectedReportsRoute: ProtectedReportsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedZonesRoute: ProtectedZonesRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDonationsDonationIdRoute: ProtectedDonationsDonationIdRoute,
  ProtectedUsersUserIdRoute: ProtectedUsersUserIdRoute,
  ProtectedDonationsIndexRoute: ProtectedDonationsIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
